### PR TITLE
More es6-ish syntax

### PR DESCRIPTION
**Pull request by robertleeplummerjr**

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Mostly just opened to improve es6 syntax.  Open to feedback, be brutal.

**Comment by unbornchikken** [comment]
Why have you mixed up single and double quotes?

**Comment by robertleeplummerjr** [comment]
Node (at least es6+) generally uses single quotes, and I didn't want to mess with the license area.
Grabbed at random: https://nodejs.org/dist/latest-v6.x/docs/api/console.html

**Comment by unbornchikken** [comment]
Ok, but this project uses double quotes.

**Comment by unbornchikken** [comment]
On the other hand, I'm using ES6 syntax supported by the 4.x branch of node. Why? Because, if you take a look at the code, there is a feature testing in the index files. If there is support for ES6 constructs **used by this project** then native ES6 source used instead of transpiled files. And native means faster.

Once Node 6 stabilizes, and earns its LTS status, I'll will make the source more (which means 100%) ES6ish. But until then, the transitional syntax stays.

And there is a conceptual error in your PR. There is a reason why scope uses functions instead of lambdas. Inside scope, function context's (this) is the scope object, and you can escape values from it by using this.result(...). Kinda jQuery funtions where **this** is the actual jQuery object.

I know it's not that obvious because those are not very well documented features. But I'm in the middle of the process of a complete rewrite, to make this library more faster and non blocking (https://github.com/arrayfire/arrayfire-js/issues/9) so many things and almost all of the current code will get changed or replaced by other construct eventually.

So I'm closing this PR, but please keep in touch, because in the next version my aim is to make this project more contributor friendly, and your help will be appreciated there.

**Comment by robertleeplummerjr** [comment]
Understood, and I look forward to contributing in the future.  Cannot wait to see your new additions!

**Pull request closed without merging**
